spring.application.name=batch2_data_jpa_reservation_service
spring.datasource.url=jdbc:h2:~/testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.org.springframework.security=info

management.endpoints.web.exposure.include=*
