spring.application.name=customer_service
spring.datasource.url=jdbc:h2:file:~/testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.data.jpa =trace
#logging.level.orm.jdbc.bind=debug
#logging.level.org.hibernate.SQL=debug

